"""从客户资料文本中确定性提取客户官网，不调用 AI。"""

from __future__ import annotations

import re

from pathlib import Path
from urllib.parse import urlsplit, urlunsplit


AUTO_GENERATED_MARKER = "# AUTO-GENERATED BY main.py"

STRONG_WEBSITE_LABELS = (
    "推广网站域名",
    "推广网站",
    "客户官网",
    "客户网站",
    "公司官网",
    "公司网站",
    "官方网站",
    "官网地址",
    "网站地址",
    "official website",
    "company website",
    "website url",
    "website address",
)

WEAK_WEBSITE_LABELS = (
    "官网",
    "website",
)

EXCLUDED_CONTEXT_LABELS = (
    "竞争对手",
    "国内外竞争",
    "竞品",
    "论坛/网站",
    "论坛或网站",
    "相关论坛",
    "历史广告",
    "参考网站",
)

COLLECTION_FORM_NAME_HINTS = (
    "信息采集",
    "采集表",
    "调查表",
    "问卷",
    "brief",
    "questionnaire",
)

URL_OR_DOMAIN_PATTERN = re.compile(
    r"(?<![@\w])("  # 排除邮箱中的域名
    r"(?:https?://|www\.)[^\s|<>\"']+"
    r"|"
    r"(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+"
    r"[a-z]{2,}(?::\d{2,5})?(?:/[^\s|<>\"']*)?"
    r")",
    flags=re.IGNORECASE,
)

TRAILING_PUNCTUATION = ".,;:!?，。；：！？、）)]}>\"'"


def _normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", str(text or "").replace("\u00a0", " ")).strip()


def _matching_label(line: str, labels: tuple[str, ...]) -> str | None:
    lower_line = line.lower()

    for label in labels:
        if label.lower() in lower_line:
            return label

    return None


def _is_excluded_context(line: str) -> bool:
    return _matching_label(line, EXCLUDED_CONTEXT_LABELS) is not None


def normalize_website_url(value: str) -> str | None:
    """把裸域名规范化为可抓取的 http(s) URL。"""
    value = _normalize_space(value).rstrip(TRAILING_PUNCTUATION)

    if not value:
        return None

    if not re.match(r"^https?://", value, flags=re.IGNORECASE):
        value = "https://" + value

    try:
        parsed = urlsplit(value)
    except ValueError:
        return None

    hostname = (parsed.hostname or "").lower()

    if not hostname or "." not in hostname or " " in hostname:
        return None

    netloc = hostname

    try:
        port = parsed.port
    except ValueError:
        return None

    if port:
        netloc += f":{port}"

    path = parsed.path or ""

    return urlunsplit((parsed.scheme.lower(), netloc, path, parsed.query, ""))


def _extract_urls_from_text(text: str) -> list[str]:
    urls = []

    for match in URL_OR_DOMAIN_PATTERN.finditer(text):
        url = normalize_website_url(match.group(1))

        if url and url not in urls:
            urls.append(url)

    return urls


def _looks_like_collection_form(source_name: str) -> bool:
    lower_name = source_name.lower()
    return any(hint.lower() in lower_name for hint in COLLECTION_FORM_NAME_HINTS)


def extract_client_website_urls(documents: list[dict]) -> list[dict]:
    """
    从已成功读取的源文档中提取客户官网。

    documents 的每项格式：
    {"source": "相对文件名", "content": "提取后的文本"}
    """
    records = []
    seen_urls = set()

    for document in documents:
        source = str(document.get("source", ""))
        content = str(document.get("content", ""))
        lines = [line.strip() for line in content.splitlines()]
        is_collection_form = _looks_like_collection_form(source)

        for index, raw_line in enumerate(lines):
            line = _normalize_space(raw_line)

            if not line or _is_excluded_context(line):
                continue

            label = _matching_label(line, STRONG_WEBSITE_LABELS)

            # “官网”这类弱标签只在信息采集表靠前位置启用，防止把正文中
            # “官网产品页”或竞品分析说明误判成客户官网字段。
            if label is None and is_collection_form and index < 50:
                label = _matching_label(line, WEAK_WEBSITE_LABELS)

            if label is None:
                continue

            candidate_texts = [line]

            # 兼容 Word 表格中字段名和值被拆成相邻两行的情况。
            if not _extract_urls_from_text(line):
                for next_index in range(index + 1, min(index + 3, len(lines))):
                    next_line = _normalize_space(lines[next_index])

                    if not next_line:
                        continue

                    if _is_excluded_context(next_line):
                        break

                    if _matching_label(
                        next_line,
                        STRONG_WEBSITE_LABELS + WEAK_WEBSITE_LABELS,
                    ):
                        break

                    candidate_texts.append(next_line)
                    break

            for candidate_text in candidate_texts:
                for url in _extract_urls_from_text(candidate_text):
                    if url in seen_urls:
                        continue

                    seen_urls.add(url)
                    records.append({
                        "url": url,
                        "source": source,
                        "label": label,
                    })

    return records


def update_website_urls_file(output_dir: Path, records: list[dict]) -> str:
    """
    更新自动生成的 website_urls.txt。

    返回状态：written / removed_stale / preserved_manual / absent。
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "website_urls.txt"

    if records:
        lines = [AUTO_GENERATED_MARKER, "# 从客户资料中的明确官网字段提取，请人工复核"]

        for record in records:
            lines.append(
                f"# 来源: {record['source']} | 字段: {record['label']}"
            )
            lines.append(record["url"])

        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return "written"

    if not path.exists():
        return "absent"

    existing_text = path.read_text(encoding="utf-8")

    if existing_text.startswith(AUTO_GENERATED_MARKER):
        path.unlink()
        return "removed_stale"

    return "preserved_manual"


def website_url_file_has_values(path: Path) -> bool:
    if not path.exists():
        return False

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()

        if line and not line.startswith("#"):
            return True

    return False


def resolve_website_urls_path(
    project_root: Path,
    project_name: str,
) -> tuple[Path | None, str | None]:
    """优先返回 outputs 新路径，再回退 uploads 旧路径。"""
    output_path = project_root / "outputs" / project_name / "website_urls.txt"
    legacy_path = project_root / "uploads" / project_name / "website_urls.txt"

    if website_url_file_has_values(output_path):
        return output_path, "outputs"

    if website_url_file_has_values(legacy_path):
        return legacy_path, "uploads_legacy"

    return None, None
